apiVersion: v2
appVersion: 0.2.0
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.26.2
dependencies:
  - name: gitops-runtime
    repository: oci://quay.io/codefresh   # /dev
    version: 0.26.2
