apiVersion: v2
appVersion: 0.1.76
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.25.1
dependencies:
  - name: gitops-runtime
    repository: oci://quay.io/codefresh/dev   # /dev
    version: 0.25.1
