apiVersion: v2
appVersion: 0.2.1
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.27.1
dependencies:
  - name: gitops-runtime
    repository: oci://quay.io/codefresh   # /dev
    version: 0.27.1
